apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstapp1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: firstapp1
  template:
    metadata:
      labels:
        app: firstapp1
    spec:
      containers:
        - name: firstapp1-container
          image: raoabhijeet123/firstapp1:latest
          ports:
            - containerPort: 80

