apiVersion: apps/v1
kind: Diieployment
metadata:
  name: firstapp1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: firstapp1
  template:
    metadata:
      labels:
        app: firstapp1
    spec:
      containers:
        - name: firstapp1-container
          image: registry1750534887072.azurecr.io/image-workflow-1750534825555'
          ports:
            - containerPort: 80

